services:
  postgres:
    image: postgres:16

    container_name: dottie_test_db

    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dottieTestDB

    ports:
      - "5432:5432"
